{
 "title": "Strada - Observability Dashboard",
 "tags": [
  "prometheus-net",
  "net",
  "prometheus",
  ".net",
  ".net core"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "app",
    "query": "label_values(http_requests_received_total, app)"
   },
   {
    "name": "pods",
    "label": "pods",
    "query": "label_values(http_requests_received_total{app =~ \"$app\"}, kubernetes_pod_name)"
   },
   {
    "name": "controllers",
    "label": "controllers",
    "query": "label_values(http_requests_received_total{app =~ \"$app\", kubernetes_pod_name=~ \"$pods\"}, controller)"
   }
  ]
 },
 "panels": [
  {
   "title": "Nombre des requêtes HTTP / controlleur",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_received_total{ app=~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller =~ \"$controllers\" }) by (controller) ",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Nombre des requêtes  HTTP / type de retour",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_received_total{ code!=\"200\", app=~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller =~ \"$controllers\"}) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Moyenne des requêtes HTTP / Type de retour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{app=~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller =~ \"$controllers\"}[1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Requêtes non traitées (Retour 4xx - 5xx)",
   "type": "graph",
   "description": "4xx and 5xx status codes",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller =~ \"$controllers\", code =~ \"5\\\\d\\\\d|4\\\\d\\\\d\"}[1m])) by (controller)",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "sum(rate(http_requests_received_total{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller = \"\", code =~ \"5\\\\d\\\\d|4\\\\d\\\\d\"}[1m])) by (controller)",
     "legendFormat": "{{kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Moyenne des requêtes HTTP / Controlleur",
   "type": "graph",
   "description": "Counts all requests, both successful and failed",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{app=~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller =~ \"$controllers\"}[1m])) by (controller)",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "sum(rate(http_requests_received_total{app=~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller = \"\"}[1m]))",
     "legendFormat": "(None)"
    }
   ]
  },
  {
   "title": "Requêtes HTTP traitées (Retour 200)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller =~ \"$controllers\", code =~ \"200\"} [1m])) by(controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Durées des requêtes HTTP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{ app=~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller =~ \"$controllers\" }[1m])) by (controller)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Bugs non catchés",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Exceptions{app=~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller =~ \"$controllers\"}",
     "legendFormat": "{{controller}} - {{action}}"
    }
   ]
  },
  {
   "title": "Request duration (controller-handled requests only)",
   "type": "heatmap",
   "description": "Does NOT include requests that were not mapped to an ASP.NET Core controller!",
   "gridPos": { "h": 18, "w": 9, "x": 15, "y": 32 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller =~ \"$controllers\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Mémoire allouée",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{ app=~\"$app\", kubernetes_pod_name=~\"$pods\"} /1024/1024",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Nombre totale de  threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_num_threads{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Healthchecks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aspnetcore_healthcheck_status {app=~\"$app\", kubernetes_pod_name=~\"$pods\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "GC collection count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dotnet_collection_count_total{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name }}-Generation-{{generation}}"
    }
   ]
  }
 ]
}